#!/usr/bin/env node
import {
  cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const trackDir = join(ROOT, "tracks", "solar-system");
const planPath = join(trackDir, "_run_plan.json");
const trackPath = join(trackDir, "_track.json");
const frontendGames = join(ROOT, "frontend", "games", "solar-system");
const frontendData = join(ROOT, "frontend", "assets", "solar-system-data.js");
const migrationPath = join(ROOT, "db", "migrations", "0005_seed_solar_system.sql");
const plan = JSON.parse(readFileSync(planPath, "utf8"));
const track = JSON.parse(readFileSync(trackPath, "utf8"));
const codeExt = /\.(html?|js|mjs|css)$/i;

function walk(dir, base = dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    const stat = statSync(path);
    if (stat.isDirectory()) out.push(...walk(path, base));
    else out.push({ rel: path.slice(base.length + 1), abs: path, bytes: stat.size });
  }
  return out;
}

function localRefs(html) {
  const refs = [];
  const pattern = /(?:src|href)\s*=\s*["']([^"']+)["']/gi;
  let match;
  while ((match = pattern.exec(html))) {
    const value = match[1].trim();
    if (!value || /^(data:|https?:|\/\/|#|mailto:)/i.test(value)) continue;
    refs.push(value.split(/[?#]/)[0]);
  }
  return [...new Set(refs)];
}

const missing = plan.runs.filter((run) => !existsSync(join(trackDir, run.slug, "index.html")));
if (missing.length) {
  throw new Error(`not ready: ${missing.length} runs missing index.html: ${missing.map((r) => r.slug).join(", ")}`);
}

const entrants = plan.runs.map((run) => {
  const base = join(trackDir, run.slug);
  const files = walk(base);
  const html = readFileSync(join(base, "index.html"), "utf8");
  const brokenRefs = localRefs(html).filter((ref) => !existsSync(join(base, ref)));
  if (brokenRefs.length) throw new Error(`${run.slug} has missing local refs: ${brokenRefs.join(", ")}`);
  let codeLines = 0;
  for (const file of files) {
    if (codeExt.test(file.rel)) codeLines += readFileSync(file.abs, "utf8").split("\n").length;
  }
  return {
    dir: run.slug,
    display_name: run.model,
    vendor: run.vendor,
    harness: run.harness,
    machine: run.machine,
    files: files.length,
    bytes: files.reduce((sum, file) => sum + file.bytes, 0),
    code_lines: codeLines,
    loads_ok: true,
    broken_refs: [],
  };
});

rmSync(frontendGames, { recursive: true, force: true });
mkdirSync(frontendGames, { recursive: true });
for (const entrant of entrants) {
  cpSync(join(trackDir, entrant.dir), join(frontendGames, entrant.dir), { recursive: true });
}

const publicData = {
  track: "solar-system",
  title_zh: track.title_zh,
  title_en: track.title_en,
  prompt: track.prompt,
  status: "ready_for_publish",
  generated_at: new Date().toISOString(),
  entrants,
};
writeFileSync(
  frontendData,
  "/* Generated by scripts/finalize_solar_system.mjs after all artifact checks pass. */\n" +
    "window.SOLAR_SYSTEM_DATA = " + JSON.stringify(publicData, null, 2) + ";\n",
);

const sql = [
  "-- 0005_seed_solar_system.sql",
  "-- Generated only after all 15 archived artifacts passed index/ref checks.",
  "",
  "INSERT OR IGNORE INTO participants (track, dir, active) VALUES",
  entrants.map((entrant, index) =>
    `  ('solar-system', '${entrant.dir.replaceAll("'", "''")}', 1)${index === entrants.length - 1 ? ";" : ","}`
  ).join("\n"),
  "",
].join("\n");
writeFileSync(migrationPath, sql);

track.status = "ready_for_publish";
track.status_label = "READY / 待最终验收发布";
track.completed_runs = entrants.length;
track.entrants = entrants.map(({ dir, display_name, vendor, harness, machine }) => ({
  dir, display_name, vendor, harness, machine,
}));
track.disclosure = "15 份归档作品均已检测 index.html 和本地依赖;仍需浏览器验收后才可正式发布";
writeFileSync(trackPath, JSON.stringify(track, null, 2) + "\n");
console.log(`prepared ${entrants.length} verified artifacts, frontend copies and ${migrationPath}`);
