#!/usr/bin/env node
import {
  cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const trackDir = join(ROOT, "tracks", "solar-system");
const planPath = join(trackDir, "_run_plan.json");
const trackPath = join(trackDir, "_track.json");
const frontendGames = join(ROOT, "frontend", "games", "solar-system");
const frontendData = join(ROOT, "frontend", "assets", "solar-system-data.js");
const migrationPath = join(ROOT, "db", "migrations", "0005_seed_solar_system.sql");
const plan = JSON.parse(readFileSync(planPath, "utf8"));
const track = JSON.parse(readFileSync(trackPath, "utf8"));
const codeExt = /\.(html?|js|mjs|css)$/i;
const partial = process.argv.includes("--partial");

function walk(dir, base = dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    const stat = statSync(path);
    if (stat.isDirectory()) out.push(...walk(path, base));
    else out.push({ rel: path.slice(base.length + 1), abs: path, bytes: stat.size });
  }
  return out;
}

function localRefs(html) {
  const refs = [];
  const pattern = /(?:src|href)\s*=\s*["']([^"']+)["']/gi;
  let match;
  while ((match = pattern.exec(html))) {
    const value = match[1].trim();
    if (!value || /^(data:|https?:|\/\/|#|mailto:)/i.test(value)) continue;
    refs.push(value.split(/[?#]/)[0]);
  }
  return [...new Set(refs)];
}

const available = plan.runs.filter((run) => existsSync(join(trackDir, run.slug, "index.html")));
const missing = plan.runs.filter((run) => !available.includes(run));
if (!available.length) {
  throw new Error("not ready: no archived solar-system artifact has index.html");
}
if (!partial && missing.length) {
  throw new Error(`not ready: ${missing.length} runs missing index.html: ${missing.map((r) => r.slug).join(", ")}`);
}

const entrants = available.map((run) => {
  const base = join(trackDir, run.slug);
  const files = walk(base);
  const html = readFileSync(join(base, "index.html"), "utf8");
  const brokenRefs = localRefs(html).filter((ref) => !existsSync(join(base, ref)));
  if (brokenRefs.length) throw new Error(`${run.slug} has missing local refs: ${brokenRefs.join(", ")}`);
  let codeLines = 0;
  for (const file of files) {
    if (codeExt.test(file.rel)) codeLines += readFileSync(file.abs, "utf8").split("\n").length;
  }
  return {
    dir: run.slug,
    display_name: run.model,
    vendor: run.vendor,
    harness: run.harness,
    machine: run.machine,
    files: files.length,
    bytes: files.reduce((sum, file) => sum + file.bytes, 0),
    code_lines: codeLines,
    loads_ok: run.browser_status !== "runtime_error",
    runtime_issue: run.runtime_issue || null,
    human_code_edits: run.human_code_edits || 0,
    maintenance_note: run.maintenance_note || null,
    broken_refs: [],
  };
});

rmSync(frontendGames, { recursive: true, force: true });
mkdirSync(frontendGames, { recursive: true });
for (const entrant of entrants) {
  cpSync(join(trackDir, entrant.dir), join(frontendGames, entrant.dir), { recursive: true });
}

const complete = entrants.length === plan.runs.length;
const live = complete && plan.status === "completed_verified";
const maintenanceEdits = entrants.reduce((sum, entrant) => sum + entrant.human_code_edits, 0);
const publicData = {
  track: "solar-system",
  title_zh: track.title_zh,
  title_en: track.title_en,
  prompt: track.prompt,
  status: live ? "live" : complete ? "ready_for_publish" : "collecting",
  blind_voting_enabled: entrants.length >= 2,
  generated_at: new Date().toISOString(),
  entrants,
};
writeFileSync(
  frontendData,
  "/* Generated by scripts/finalize_solar_system.mjs from verified archived artifacts. */\n" +
    "window.SOLAR_SYSTEM_DATA = " + JSON.stringify(publicData, null, 2) + ";\n",
);

const sql = [
  "-- 0005_seed_solar_system.sql",
  "-- Generated only from verified archived artifacts; review before applying.",
  "-- A single participant may be registered, but pairing requires at least two active participants.",
  "",
  "INSERT OR IGNORE INTO participants (track, dir, active) VALUES",
  entrants.map((entrant, index) =>
    `  ('solar-system', '${entrant.dir.replaceAll("'", "''")}', 1)${index === entrants.length - 1 ? ";" : ","}`
  ).join("\n"),
  "",
].join("\n");
writeFileSync(migrationPath, sql);

track.status = live ? "live" : complete ? "ready_for_publish" : "collecting";
track.status_label = live ? "LIVE / 15 份作品已上线" : complete ? "READY / 待最终验收发布" : "COLLECTING / 已有真实作品";
track.completed_runs = entrants.length;
track.entrants = entrants.map(({ dir, display_name, vendor, harness, machine }) => ({
  dir, display_name, vendor, harness, machine,
}));
track.publication_gate = "单个真实作品完成归档、依赖检查和浏览器验收后即可先上线试玩;至少 2 份真实作品才启用盲评和排行榜";
track.disclosure = complete
  ? `15 份归档作品均已检测 index.html、本地依赖和浏览器加载;其中 ${maintenanceEdits} 处最小上线修复已在参赛记录中披露`
  : entrants.length >= 2
    ? `当前 ${entrants.length} 份真实作品已完成归档、文件检查和浏览器验收;试玩、完整排序、匿名盲评和排行榜已开放，赛道继续收集其余计划运行位`
    : `当前 ${entrants.length} 份真实作品已完成归档和文件检查;赛道继续收集，未满 2 份时不开放盲评或排行榜`;
writeFileSync(trackPath, JSON.stringify(track, null, 2) + "\n");
console.log(`prepared ${entrants.length} verified artifact(s); blind voting ${entrants.length >= 2 ? "eligible" : "disabled"}`);
